[features]
seeds = false
skip-lint = false
[programs.localnet]
simple_dapp = "AtuM7Xpm1RV6tZPdW4H6m5g2erKKZuJk34Lg45UKqhnx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ronnelrobles/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.js"
